project_id = "gkvvtfqfggddzotxltxf"

[functions.import-csv-leads]
verify_jwt = true

[functions.chatwoot-auth]
verify_jwt = false

[functions.bitrix-webhook]
verify_jwt = false

[functions.chatwoot-transfer]
verify_jwt = false
